### ISSUE TITLE
Question: Can this replace the standard-library classes within fmt?

### ISSUE THREAD

**Issue by eyalroz** [robhz786/outbuf#1]
I'm trying to adapt (most of) the [fmt formatting library](https://github.com/fmtlib/fmt/) for use in some embedded(ish) setting, where the C++ standard library is not available.

What remains for me to replace, mostly, is `std::basic_streambuf` and `std::basic_ostream`.

Question: Do you believe the classes in this library could be used, or adapted for use, instead of those two?

**Comment by robhz786** [comment]
Hi Eyal,
Yes, I think It could. 
I don't know how fmt is implemented. But I don't see why outbuf couldn't be used there.
However, I kind of abandoned the project due to lack of interest.

**Comment by eyalroz** [comment]
> Yes, I think It could.

So, no dependence on `<ios>`, `<istream>`, `<ostream>`, `<string>`, `<locale>` and all of that stuff in the standard library?

**Comment by eyalroz** [comment]
> I kind of abandoned the project due to lack of interest.

Yours, or others' ?

**Comment by robhz786** [comment]
> > Yes, I think It could.
> 
> So, no dependence on `<ios>`, `<istream>`, `<ostream>`, `<string>`, `<locale>` and all of that stuff in the standard library?

`outbuf.hpp` only depends on `<cstring>`,  `<cwchar>` and `<cstdint>`. This is the only header you really need. The other headers files are optional and you can even delete from your codebase. 

`outbuf/iterator.hpp` additionally depends on `<iterator>`. This header provides the outbuf_iterator which is an output iterator adapter to the `outbuf` class template. This can be useful when using fmtlib. But you don't have to use it.

`outbuf/string.hpp` depends on `<string>`. It provides a subclass of outbuf that writes to `std::basic_string`. You can ignore/delete this file. 

`outbuf/streambuf.hpp` depends on `<streambuf>`.  It provides a subclass of `outbuf` that writes to `std::basic_streambuf`. You can ignore/delete this file. 

`outbuf/cfile.hpp` depends on <cstdio>. It provides a subclass of `outbuf` that writes to `FILE*`. You can ignore/delete this file.

**Comment by robhz786** [comment]
> > I kind of abandoned the project due to lack of interest.
> 
> Yours, or others' ?

Outbuf was born in another library: https://github.com/robhz786/strf
I isolated outbuf from there to make it easier to be accepted in Boost.
I didn't get much enthusiasm from boost, though I didn't receive any criticism either.
Anyway, I decided to make strf not part of boost, and leave outbuf as part of strf.

Strf is a header-only formatting library that I'm working actively.
It did not yet reach the 1.0 version. But it's almost there.
I have plans to try to make it usable in bare-metal environments,
though I'm not experienced with embedded development.

Perhaps would you be interested in using strf instead of fmt?

**Comment by eyalroz** [comment]
> Perhaps would you be interested in using strf instead of fmt?

I might. So, to elaborate a bit on my goal: I want better debug-printing capability in [CUDA](https://en.wikipedia.org/wiki/CUDA) GPU-side code. But the only "primitive" we have there is a (hardware-assisted) `printf()` function. The functionality I (think I) want is:

* `snprintf()`, or at least a variadic-template equivalent thereof
* an ostream on top of that custom `printf()`, which prints only when you flush it explicitly.
* stringstream-like ostreams 

and the code doesn't need to be header-only or anything like that. Also, locale support is not important (and perhaps it's better not to have it).

Now, GPU-side ("device-side") code in CUDA cannot use standard library code, except for `constexpr` functions - even if that code would work on the GPU (e.g. `int foo(int x) { return x+1; }` can't be used, unless it's marked `constexpr` or `__device__`). That means I can't just inherit an `std::ostream`, or call `std::snprintf()` even if those don't do any file I/O.

So, my thought was to adapt `fmt`, because supposedly it's a standalone alternative to the standard library offerings - and to cut out everything involving files, std::string's and so on. but as I look through the code I realize dependent it is on the standard library - basic ostreams, basic streabufs, ios and locale. So, that route would be difficult to follow.

**Comment by robhz786** [comment]
>     *  `snprintf()`, or at least a variadic-template equivalent thereof
strf provides that. The sintax is : `strf::to(dest, dest_size) ( arguments ... )`

>     *  an ostream on top of that custom `printf()`, which prints only when you flush it explicitly.
> 
>     *  stringstream-like ostreams
class `strf::outbuf` ( which is basically the of the outbuf library ) can be used. This is an abstract class. Just like `std::strembuf`, it contains an internal buffer that is flushed when is full, or when `recycle()` member function is called. Unlike `std::streambuf` and `std::ostream`, it is simple to implement a concrete class that derives from `outbuf`. So you will need to create an outbuf that has a sufficiently large buffer, so that it is only flushed when you call `recycle()`. 

However the library still don't provide a way to just write to an `outbuf&`, but this is already my to-do list and I will implement it in the next days.
``
strf::outbuf& dest = // ...;
strf::to(dest) (args ... ); // print args to dest
strf::to(dest) (other_args ... ); // print more args to dest
dest.recycle(); // flush content when desired; 
``
Is kinda this what you need ? 

> and the code doesn't need to be header-only or anything like that. 

It can be used as header-only or as a static library. Your choice. In the later case, you need to define the macro `STRF_SEPARATE_COMPILATION`

> Also, locale support is not important (and perhaps it's better not to have it).

Indeed, it does not use locale.
 
> So, my thought was to adapt `fmt`, because supposedly it's a standalone alternative to the standard library offerings - and to cut out everything involving files, std::string's and so on. but as I look through the code I realize dependent it is on the standard library - basic ostreams, basic streabufs, ios and locale. So, that route would be difficult to follow.

Strf does not depends on ostream, streambuf, ios nor locale. But it uses `char_traits` in many places. So maybe this has to be replaced.

I have just created in the strf repository a branch "feature/cuda" where we can work together to adapt strf to cuda, if you wish. I'm unable help you more today. But I'm available on sunday. 

You can also contact me through my email: robhz786 \<at\> gmail.com

**Comment by eyalroz** [comment]
Will send you an email soon. This seems like a potentially fruitful course of action...
